var classes = [
    {
        "name": "Orders\\Infra\\EventHandlers\\OrderCreatedHandler",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "supports",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "Orders\\Infra\\EventHandlers\\EventHandlerInterface",
            "Orders\\Ports\\Outbound\\ProductsServiceInterface",
            "DomainException"
        ],
        "parents": [],
        "implements": [
            "Orders\\Infra\\EventHandlers\\EventHandlerInterface"
        ],
        "lcom": 3,
        "length": 28,
        "vocabulary": 14,
        "volume": 106.61,
        "difficulty": 4,
        "effort": 426.42,
        "level": 0.25,
        "bugs": 0.04,
        "time": 24,
        "intelligentContent": 26.65,
        "number_operators": 8,
        "number_operands": 20,
        "number_operators_unique": 4,
        "number_operands_unique": 10,
        "cloc": 0,
        "loc": 23,
        "lloc": 23,
        "mi": 55.56,
        "mIwoC": 55.56,
        "commentWeight": 0,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 3,
        "totalDataComplexity": 4.5,
        "totalSystemComplexity": 7.5,
        "package": "Orders\\Infra\\EventHandlers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Orders\\Infra\\EventHandlers\\OrderUpdatedHandler",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "supports",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Orders\\Infra\\EventHandlers\\EventHandlerInterface"
        ],
        "parents": [],
        "implements": [
            "Orders\\Infra\\EventHandlers\\EventHandlerInterface"
        ],
        "lcom": 2,
        "length": 7,
        "vocabulary": 3,
        "volume": 11.09,
        "difficulty": 4,
        "effort": 44.38,
        "level": 0.25,
        "bugs": 0,
        "time": 2,
        "intelligentContent": 2.77,
        "number_operators": 3,
        "number_operands": 4,
        "number_operators_unique": 2,
        "number_operands_unique": 1,
        "cloc": 1,
        "loc": 15,
        "lloc": 14,
        "mi": 86.88,
        "mIwoC": 67.41,
        "commentWeight": 19.47,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 6,
        "totalSystemComplexity": 6,
        "package": "Orders\\Infra\\EventHandlers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Orders\\Infra\\EventPublisher",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "publish",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "logEvent",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 9,
        "ccn": 7,
        "ccnMethodMax": 5,
        "externals": [
            "Orders\\Ports\\Outbound\\EventPublisherInterface",
            "Psr\\Log\\LoggerInterface",
            "Orders\\Infra\\EventHandlers\\EventHandlerInterface"
        ],
        "parents": [],
        "implements": [
            "Orders\\Ports\\Outbound\\EventPublisherInterface"
        ],
        "lcom": 1,
        "length": 38,
        "vocabulary": 16,
        "volume": 152,
        "difficulty": 3.69,
        "effort": 561.23,
        "level": 0.27,
        "bugs": 0.05,
        "time": 31,
        "intelligentContent": 41.17,
        "number_operators": 6,
        "number_operands": 32,
        "number_operators_unique": 3,
        "number_operands_unique": 13,
        "cloc": 1,
        "loc": 24,
        "lloc": 23,
        "mi": 69.63,
        "mIwoC": 54.08,
        "commentWeight": 15.55,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.22,
        "relativeSystemComplexity": 25.22,
        "totalStructuralComplexity": 75,
        "totalDataComplexity": 0.67,
        "totalSystemComplexity": 75.67,
        "package": "Orders\\Infra\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Orders\\Infra\\Http\\ProductsHttpClientFactory",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "GuzzleHttp\\Client",
            "GuzzleHttp\\Client"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 11,
        "vocabulary": 9,
        "volume": 34.87,
        "difficulty": 0.63,
        "effort": 21.79,
        "level": 1.6,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 55.79,
        "number_operators": 1,
        "number_operands": 10,
        "number_operators_unique": 1,
        "number_operands_unique": 8,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 69.37,
        "mIwoC": 69.37,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 2,
        "package": "Orders\\Infra\\Http\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Orders\\Infra\\Http\\HandlerExceptionResolver",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "resolve",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 5,
        "ccnMethodMax": 5,
        "externals": [
            "Psr\\Http\\Message\\ResponseInterface",
            "Throwable",
            "Psr\\Http\\Message\\ResponseInterface",
            "Orders\\Infra\\Http\\JsonResponseHelper",
            "Orders\\Infra\\Http\\JsonResponseHelper",
            "Orders\\Infra\\Http\\JsonResponseHelper",
            "Orders\\Infra\\Http\\JsonResponseHelper"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 26,
        "vocabulary": 9,
        "volume": 82.42,
        "difficulty": 4.5,
        "effort": 370.88,
        "level": 0.22,
        "bugs": 0.03,
        "time": 21,
        "intelligentContent": 18.32,
        "number_operators": 8,
        "number_operands": 18,
        "number_operators_unique": 3,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 17,
        "lloc": 17,
        "mi": 59.07,
        "mIwoC": 59.07,
        "commentWeight": 0,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 6,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 6,
        "package": "Orders\\Infra\\Http\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "Orders\\Infra\\Http\\ProductsClient",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "reserveProducts",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "releaseReservation",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "Orders\\Ports\\Outbound\\ProductsServiceInterface",
            "GuzzleHttp\\Client",
            "Orders\\Adapters\\Outbound\\ProductsAdapterInterface"
        ],
        "parents": [],
        "implements": [
            "Orders\\Ports\\Outbound\\ProductsServiceInterface"
        ],
        "lcom": 2,
        "length": 48,
        "vocabulary": 20,
        "volume": 207.45,
        "difficulty": 4.5,
        "effort": 933.54,
        "level": 0.22,
        "bugs": 0.07,
        "time": 52,
        "intelligentContent": 46.1,
        "number_operators": 12,
        "number_operands": 36,
        "number_operators_unique": 4,
        "number_operands_unique": 16,
        "cloc": 0,
        "loc": 27,
        "lloc": 27,
        "mi": 52.15,
        "mIwoC": 52.15,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.63,
        "relativeSystemComplexity": 64.63,
        "totalStructuralComplexity": 192,
        "totalDataComplexity": 1.89,
        "totalSystemComplexity": 193.89,
        "package": "Orders\\Infra\\Http\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Orders\\Infra\\Http\\ExceptionHandlingMiddleware",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "process",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Psr\\Http\\Server\\MiddlewareInterface",
            "Psr\\Http\\Message\\ResponseFactoryInterface",
            "Psr\\Http\\Message\\ResponseInterface",
            "Psr\\Http\\Message\\ServerRequestInterface",
            "Psr\\Http\\Server\\RequestHandlerInterface",
            "Orders\\Infra\\Http\\HandlerExceptionResolver"
        ],
        "parents": [],
        "implements": [
            "Psr\\Http\\Server\\MiddlewareInterface"
        ],
        "lcom": 2,
        "length": 14,
        "vocabulary": 9,
        "volume": 44.38,
        "difficulty": 2.5,
        "effort": 110.95,
        "level": 0.4,
        "bugs": 0.01,
        "time": 6,
        "intelligentContent": 17.75,
        "number_operators": 4,
        "number_operands": 10,
        "number_operators_unique": 3,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 16,
        "lloc": 16,
        "mi": 61.93,
        "mIwoC": 61.93,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.88,
        "relativeSystemComplexity": 9.88,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 1.75,
        "totalSystemComplexity": 19.75,
        "package": "Orders\\Infra\\Http\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Orders\\Infra\\Http\\JsonResponseHelper",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "success",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "error",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Psr\\Http\\Message\\ResponseInterface",
            "Psr\\Http\\Message\\ResponseInterface",
            "Psr\\Http\\Message\\ResponseInterface",
            "Psr\\Http\\Message\\ResponseInterface"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 23,
        "vocabulary": 10,
        "volume": 76.4,
        "difficulty": 1.17,
        "effort": 89.14,
        "level": 0.86,
        "bugs": 0.03,
        "time": 5,
        "intelligentContent": 65.49,
        "number_operators": 2,
        "number_operands": 21,
        "number_operators_unique": 1,
        "number_operands_unique": 9,
        "cloc": 0,
        "loc": 14,
        "lloc": 14,
        "mi": 61.68,
        "mIwoC": 61.68,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 17,
        "totalStructuralComplexity": 32,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 34,
        "package": "Orders\\Infra\\Http\\",
        "pageRank": 0.03,
        "afferentCoupling": 5,
        "efferentCoupling": 1,
        "instability": 0.17,
        "violations": {}
    },
    {
        "name": "Orders\\Infra\\Http\\Handlers\\CloseOrderHandler",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Orders\\Ports\\Inbound\\CloseOrderUseCase",
            "Orders\\Adapters\\Inbound\\OrderJsonAdapterInterface",
            "Psr\\Http\\Message\\ResponseInterface",
            "Psr\\Http\\Message\\ServerRequestInterface",
            "Psr\\Http\\Message\\ResponseInterface",
            "Orders\\Infra\\Http\\JsonResponseHelper"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 23,
        "vocabulary": 14,
        "volume": 87.57,
        "difficulty": 2.45,
        "effort": 214.94,
        "level": 0.41,
        "bugs": 0.03,
        "time": 12,
        "intelligentContent": 35.68,
        "number_operators": 5,
        "number_operands": 18,
        "number_operators_unique": 3,
        "number_operands_unique": 11,
        "cloc": 0,
        "loc": 14,
        "lloc": 14,
        "mi": 61.13,
        "mIwoC": 61.13,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.43,
        "relativeSystemComplexity": 36.43,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 0.86,
        "totalSystemComplexity": 72.86,
        "package": "Orders\\Infra\\Http\\Handlers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Orders\\Infra\\Http\\Handlers\\GetOrderHandler",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Orders\\Ports\\Inbound\\GetOrderUseCase",
            "Psr\\Http\\Message\\ResponseInterface",
            "Psr\\Http\\Message\\ServerRequestInterface",
            "Psr\\Http\\Message\\ResponseInterface",
            "Orders\\Infra\\Http\\JsonResponseHelper"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 16,
        "vocabulary": 10,
        "volume": 53.15,
        "difficulty": 1.63,
        "effort": 86.37,
        "level": 0.62,
        "bugs": 0.02,
        "time": 5,
        "intelligentContent": 32.71,
        "number_operators": 3,
        "number_operands": 13,
        "number_operators_unique": 2,
        "number_operands_unique": 8,
        "cloc": 0,
        "loc": 13,
        "lloc": 13,
        "mi": 63.48,
        "mIwoC": 63.48,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.6,
        "relativeSystemComplexity": 16.6,
        "totalStructuralComplexity": 32,
        "totalDataComplexity": 1.2,
        "totalSystemComplexity": 33.2,
        "package": "Orders\\Infra\\Http\\Handlers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Orders\\Infra\\Http\\Handlers\\UpdateStatusHandler",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "Orders\\Ports\\Inbound\\UpdateOrderStatusUseCase",
            "Psr\\Http\\Message\\ResponseInterface",
            "Psr\\Http\\Message\\ServerRequestInterface",
            "Psr\\Http\\Message\\ResponseInterface",
            "InvalidArgumentException",
            "Orders\\Infra\\Http\\JsonResponseHelper"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 34,
        "vocabulary": 20,
        "volume": 146.95,
        "difficulty": 4.17,
        "effort": 612.27,
        "level": 0.24,
        "bugs": 0.05,
        "time": 34,
        "intelligentContent": 35.27,
        "number_operators": 9,
        "number_operands": 25,
        "number_operators_unique": 5,
        "number_operands_unique": 15,
        "cloc": 0,
        "loc": 18,
        "lloc": 18,
        "mi": 56.9,
        "mIwoC": 56.9,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 25.5,
        "totalStructuralComplexity": 50,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 51,
        "package": "Orders\\Infra\\Http\\Handlers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Orders\\Infra\\Http\\Handlers\\ListOrdersHandler",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Orders\\Ports\\Inbound\\ListOrdersUseCase",
            "Psr\\Http\\Message\\ResponseInterface",
            "Psr\\Http\\Message\\ServerRequestInterface",
            "Psr\\Http\\Message\\ResponseInterface",
            "Orders\\Infra\\Http\\JsonResponseHelper"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 12,
        "vocabulary": 8,
        "volume": 36,
        "difficulty": 1.67,
        "effort": 60,
        "level": 0.6,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 21.6,
        "number_operators": 2,
        "number_operands": 10,
        "number_operators_unique": 2,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 12,
        "lloc": 12,
        "mi": 65.43,
        "mIwoC": 65.43,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 16.5,
        "totalStructuralComplexity": 32,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 33,
        "package": "Orders\\Infra\\Http\\Handlers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Orders\\Infra\\Persistence\\OrderQueries",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 0,
        "length": 4,
        "vocabulary": 4,
        "volume": 8,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 16,
        "number_operators": 0,
        "number_operands": 4,
        "number_operators_unique": 0,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 12,
        "lloc": 12,
        "mi": 70,
        "mIwoC": 70,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Orders\\Infra\\Persistence\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Orders\\Infra\\Persistence\\Database",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPdo",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createTables",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Orders\\Infra\\Persistence\\DatabaseInterface",
            "PDO",
            "PDO"
        ],
        "parents": [],
        "implements": [
            "Orders\\Infra\\Persistence\\DatabaseInterface"
        ],
        "lcom": 1,
        "length": 24,
        "vocabulary": 13,
        "volume": 88.81,
        "difficulty": 1.82,
        "effort": 161.47,
        "level": 0.55,
        "bugs": 0.03,
        "time": 9,
        "intelligentContent": 48.85,
        "number_operators": 4,
        "number_operands": 20,
        "number_operators_unique": 2,
        "number_operands_unique": 11,
        "cloc": 0,
        "loc": 19,
        "lloc": 19,
        "mi": 58.33,
        "mIwoC": 58.33,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.67,
        "relativeSystemComplexity": 1.67,
        "totalStructuralComplexity": 3,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 5,
        "package": "Orders\\Infra\\Persistence\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Orders\\Infra\\Persistence\\OrderRepository",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "save",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "findById",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "listAll",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "Orders\\Ports\\Outbound\\OrderRepositoryInterface",
            "PDO",
            "Orders\\Adapters\\Inbound\\OrderDbAdapterInterface",
            "Orders\\Adapters\\Outbound\\OrderDbAdapterInterface",
            "Orders\\Domain\\Entities\\Order",
            "Orders\\Domain\\Entities\\Order"
        ],
        "parents": [],
        "implements": [
            "Orders\\Ports\\Outbound\\OrderRepositoryInterface"
        ],
        "lcom": 2,
        "length": 76,
        "vocabulary": 23,
        "volume": 343.79,
        "difficulty": 8.33,
        "effort": 2864.92,
        "level": 0.12,
        "bugs": 0.11,
        "time": 159,
        "intelligentContent": 41.25,
        "number_operators": 16,
        "number_operands": 60,
        "number_operators_unique": 5,
        "number_operands_unique": 18,
        "cloc": 0,
        "loc": 38,
        "lloc": 38,
        "mi": 47.38,
        "mIwoC": 47.38,
        "commentWeight": 0,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.6,
        "relativeSystemComplexity": 36.6,
        "totalStructuralComplexity": 180,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 183,
        "package": "Orders\\Infra\\Persistence\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Orders\\Adapters\\Inbound\\OrderDbAdapter",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "toOrder",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "Orders\\Adapters\\Inbound\\OrderDbAdapterInterface",
            "Orders\\Domain\\Entities\\Order",
            "RuntimeException",
            "Orders\\Domain\\ValueObjects\\Address",
            "Orders\\Domain\\ValueObjects\\Address",
            "Orders\\Domain\\ValueObjects\\Item",
            "Orders\\Domain\\ValueObjects\\OrderStatus",
            "DateTimeImmutable",
            "DateTimeImmutable",
            "Orders\\Domain\\Entities\\Order"
        ],
        "parents": [],
        "implements": [
            "Orders\\Adapters\\Inbound\\OrderDbAdapterInterface"
        ],
        "lcom": 1,
        "length": 36,
        "vocabulary": 18,
        "volume": 150.12,
        "difficulty": 4.14,
        "effort": 621.91,
        "level": 0.24,
        "bugs": 0.05,
        "time": 35,
        "intelligentContent": 36.24,
        "number_operators": 7,
        "number_operands": 29,
        "number_operators_unique": 4,
        "number_operands_unique": 14,
        "cloc": 0,
        "loc": 14,
        "lloc": 14,
        "mi": 59.22,
        "mIwoC": 59.22,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 9.5,
        "totalStructuralComplexity": 9,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 9.5,
        "package": "Orders\\Adapters\\Inbound\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 7,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Orders\\Adapters\\Inbound\\OrderJsonAdapter",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "toOrderData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Orders\\Adapters\\Inbound\\OrderJsonAdapterInterface",
            "Orders\\Domain\\Validation\\ValidationHelper",
            "Orders\\Domain\\Validation\\ValidationHelper",
            "Orders\\Domain\\Validation\\ValidationHelper",
            "Orders\\Domain\\Validation\\ValidationHelper",
            "Orders\\Domain\\ValueObjects\\Address",
            "Orders\\Domain\\ValueObjects\\Address",
            "Orders\\Domain\\ValueObjects\\Item"
        ],
        "parents": [],
        "implements": [
            "Orders\\Adapters\\Inbound\\OrderJsonAdapterInterface"
        ],
        "lcom": 1,
        "length": 32,
        "vocabulary": 12,
        "volume": 114.72,
        "difficulty": 1.41,
        "effort": 161.65,
        "level": 0.71,
        "bugs": 0.04,
        "time": 9,
        "intelligentContent": 81.41,
        "number_operators": 1,
        "number_operands": 31,
        "number_operators_unique": 1,
        "number_operands_unique": 11,
        "cloc": 0,
        "loc": 12,
        "lloc": 12,
        "mi": 61.9,
        "mIwoC": 61.9,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.33,
        "relativeSystemComplexity": 25.33,
        "totalStructuralComplexity": 25,
        "totalDataComplexity": 0.33,
        "totalSystemComplexity": 25.33,
        "package": "Orders\\Adapters\\Inbound\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Orders\\Adapters\\Outbound\\OrderDbAdapter",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "toDb",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Orders\\Adapters\\Outbound\\OrderDbAdapterInterface",
            "Orders\\Domain\\Entities\\Order"
        ],
        "parents": [],
        "implements": [
            "Orders\\Adapters\\Outbound\\OrderDbAdapterInterface"
        ],
        "lcom": 1,
        "length": 35,
        "vocabulary": 14,
        "volume": 133.26,
        "difficulty": 2.67,
        "effort": 355.35,
        "level": 0.38,
        "bugs": 0.04,
        "time": 20,
        "intelligentContent": 49.97,
        "number_operators": 3,
        "number_operands": 32,
        "number_operators_unique": 2,
        "number_operands_unique": 12,
        "cloc": 0,
        "loc": 10,
        "lloc": 10,
        "mi": 63.17,
        "mIwoC": 63.17,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.67,
        "relativeSystemComplexity": 4.67,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0.67,
        "totalSystemComplexity": 4.67,
        "package": "Orders\\Adapters\\Outbound\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Orders\\Adapters\\Outbound\\ProductsAdapter",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "itemsToRequest",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "responseToResult",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "Orders\\Adapters\\Outbound\\ProductsAdapterInterface"
        ],
        "parents": [],
        "implements": [
            "Orders\\Adapters\\Outbound\\ProductsAdapterInterface"
        ],
        "lcom": 2,
        "length": 28,
        "vocabulary": 14,
        "volume": 106.61,
        "difficulty": 4.2,
        "effort": 447.74,
        "level": 0.24,
        "bugs": 0.04,
        "time": 25,
        "intelligentContent": 25.38,
        "number_operators": 7,
        "number_operands": 21,
        "number_operators_unique": 4,
        "number_operands_unique": 10,
        "cloc": 0,
        "loc": 15,
        "lloc": 15,
        "mi": 59.61,
        "mIwoC": 59.61,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 5,
        "relativeSystemComplexity": 5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 10,
        "totalSystemComplexity": 10,
        "package": "Orders\\Adapters\\Outbound\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Orders\\Ports\\Inbound\\UpdateOrderStatusUseCase",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "execute",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Orders\\Ports\\Outbound\\OrderRepositoryInterface",
            "Orders\\Ports\\Outbound\\EventPublisherInterface",
            "Orders\\Domain\\Entities\\Order",
            "Orders\\Domain\\Exceptions\\OrderNotFoundException",
            "Orders\\Domain\\ValueObjects\\OrderStatus",
            "Orders\\Domain\\Events\\OrderUpdated"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 27,
        "vocabulary": 12,
        "volume": 96.79,
        "difficulty": 5.25,
        "effort": 508.17,
        "level": 0.19,
        "bugs": 0.03,
        "time": 28,
        "intelligentContent": 18.44,
        "number_operators": 6,
        "number_operands": 21,
        "number_operators_unique": 4,
        "number_operands_unique": 8,
        "cloc": 0,
        "loc": 20,
        "lloc": 20,
        "mi": 57.45,
        "mIwoC": 57.45,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.43,
        "relativeSystemComplexity": 36.43,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 0.86,
        "totalSystemComplexity": 72.86,
        "package": "Orders\\Ports\\Inbound\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 6,
        "instability": 0.86,
        "violations": {}
    },
    {
        "name": "Orders\\Ports\\Inbound\\GetOrderUseCase",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "execute",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Orders\\Ports\\Outbound\\OrderRepositoryInterface",
            "Orders\\Domain\\Entities\\Order",
            "Orders\\Domain\\Exceptions\\OrderNotFoundException"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 12,
        "vocabulary": 8,
        "volume": 36,
        "difficulty": 4,
        "effort": 144,
        "level": 0.25,
        "bugs": 0.01,
        "time": 8,
        "intelligentContent": 9,
        "number_operators": 4,
        "number_operands": 8,
        "number_operators_unique": 4,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 15,
        "lloc": 15,
        "mi": 63.18,
        "mIwoC": 63.18,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 4,
        "package": "Orders\\Ports\\Inbound\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "Orders\\Ports\\Inbound\\CloseOrderUseCase",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "execute",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Orders\\Ports\\Outbound\\OrderRepositoryInterface",
            "Orders\\Ports\\Outbound\\EventPublisherInterface",
            "Orders\\Domain\\Entities\\Order",
            "Orders\\Domain\\Entities\\Order",
            "Orders\\Domain\\Events\\OrderCreated"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 20,
        "vocabulary": 11,
        "volume": 69.19,
        "difficulty": 2,
        "effort": 138.38,
        "level": 0.5,
        "bugs": 0.02,
        "time": 8,
        "intelligentContent": 34.59,
        "number_operators": 2,
        "number_operands": 18,
        "number_operators_unique": 2,
        "number_operands_unique": 9,
        "cloc": 0,
        "loc": 15,
        "lloc": 15,
        "mi": 61.33,
        "mIwoC": 61.33,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.63,
        "relativeSystemComplexity": 9.63,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 1.25,
        "totalSystemComplexity": 19.25,
        "package": "Orders\\Ports\\Inbound\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8,
        "violations": {}
    },
    {
        "name": "Orders\\Ports\\Inbound\\ListOrdersUseCase",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "execute",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Orders\\Ports\\Outbound\\OrderRepositoryInterface"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 3,
        "vocabulary": 3,
        "volume": 4.75,
        "difficulty": 0.5,
        "effort": 2.38,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 9.51,
        "number_operators": 1,
        "number_operands": 2,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 0,
        "loc": 11,
        "lloc": 11,
        "mi": 72.41,
        "mIwoC": 72.41,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.75,
        "relativeSystemComplexity": 1.75,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 1.5,
        "totalSystemComplexity": 3.5,
        "package": "Orders\\Ports\\Inbound\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Orders\\Domain\\DTO\\OrderDto",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toArray",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toEventPayload",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 41,
        "vocabulary": 17,
        "volume": 167.59,
        "difficulty": 1.22,
        "effort": 204.25,
        "level": 0.82,
        "bugs": 0.06,
        "time": 11,
        "intelligentContent": 137.51,
        "number_operators": 2,
        "number_operands": 39,
        "number_operators_unique": 1,
        "number_operands_unique": 16,
        "cloc": 0,
        "loc": 15,
        "lloc": 15,
        "mi": 58.64,
        "mIwoC": 58.64,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 5,
        "relativeSystemComplexity": 5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 15,
        "totalSystemComplexity": 15,
        "package": "Orders\\Domain\\DTO\\",
        "pageRank": 0.07,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Orders\\Domain\\Exceptions\\OrderNotFoundException",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "DomainException"
        ],
        "parents": [
            "DomainException"
        ],
        "implements": [],
        "lcom": 1,
        "length": 2,
        "vocabulary": 2,
        "volume": 2,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 0,
        "number_operands": 2,
        "number_operators_unique": 0,
        "number_operands_unique": 2,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 78.06,
        "mIwoC": 78.06,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "Orders\\Domain\\Exceptions\\",
        "pageRank": 0.02,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "Orders\\Domain\\Events\\OrderUpdated",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toArray",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Orders\\Domain\\Entities\\Order",
            "Orders\\Domain\\ValueObjects\\OrderStatus",
            "DateTimeImmutable"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 26,
        "vocabulary": 14,
        "volume": 98.99,
        "difficulty": 1.75,
        "effort": 173.23,
        "level": 0.57,
        "bugs": 0.03,
        "time": 10,
        "intelligentContent": 56.57,
        "number_operators": 5,
        "number_operands": 21,
        "number_operators_unique": 2,
        "number_operands_unique": 12,
        "cloc": 0,
        "loc": 18,
        "lloc": 18,
        "mi": 58.51,
        "mIwoC": 58.51,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.67,
        "relativeSystemComplexity": 4.67,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 1.33,
        "totalSystemComplexity": 9.33,
        "package": "Orders\\Domain\\Events\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "Orders\\Domain\\Events\\OrderCreated",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toArray",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Orders\\Domain\\Entities\\Order",
            "DateTimeImmutable"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 17,
        "vocabulary": 9,
        "volume": 53.89,
        "difficulty": 1.86,
        "effort": 100.08,
        "level": 0.54,
        "bugs": 0.02,
        "time": 6,
        "intelligentContent": 29.02,
        "number_operators": 4,
        "number_operands": 13,
        "number_operators_unique": 2,
        "number_operands_unique": 7,
        "cloc": 0,
        "loc": 17,
        "lloc": 17,
        "mi": 60.9,
        "mIwoC": 60.9,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.38,
        "relativeSystemComplexity": 9.38,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 0.75,
        "totalSystemComplexity": 18.75,
        "package": "Orders\\Domain\\Events\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Orders\\Domain\\Validation\\ValidationHelper",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "requireKeys",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "requireNonEmpty",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "requireNonEmptyArray",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "requireArray",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 14,
        "ccn": 11,
        "ccnMethodMax": 4,
        "externals": [
            "InvalidArgumentException",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "InvalidArgumentException"
        ],
        "parents": [],
        "implements": [],
        "lcom": 4,
        "length": 48,
        "vocabulary": 12,
        "volume": 172.08,
        "difficulty": 13.57,
        "effort": 2335.35,
        "level": 0.07,
        "bugs": 0.06,
        "time": 130,
        "intelligentContent": 12.68,
        "number_operators": 10,
        "number_operands": 38,
        "number_operators_unique": 5,
        "number_operands_unique": 7,
        "cloc": 0,
        "loc": 30,
        "lloc": 30,
        "mi": 50.64,
        "mIwoC": 50.64,
        "commentWeight": 0,
        "kanDefect": 0.66,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 12,
        "totalSystemComplexity": 12,
        "package": "Orders\\Domain\\Validation\\",
        "pageRank": 0.11,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "Orders\\Domain\\Entities\\Order",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "calculateTotal",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getStatus",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateStatus",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toDto",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 4,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 11,
        "ccn": 8,
        "ccnMethodMax": 7,
        "externals": [
            "Orders\\Domain\\ValueObjects\\Address",
            "Orders\\Domain\\ValueObjects\\Address",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "Ramsey\\Uuid\\Uuid",
            "DateTimeImmutable",
            "DateTimeImmutable",
            "Orders\\Domain\\ValueObjects\\OrderStatus",
            "Orders\\Domain\\ValueObjects\\OrderStatus",
            "Orders\\Domain\\ValueObjects\\OrderStatusTransitions",
            "DomainException",
            "DateTimeImmutable",
            "Orders\\Domain\\DTO\\OrderDto",
            "Orders\\Domain\\DTO\\OrderDto"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 83,
        "vocabulary": 24,
        "volume": 380.55,
        "difficulty": 10,
        "effort": 3805.52,
        "level": 0.1,
        "bugs": 0.13,
        "time": 211,
        "intelligentContent": 38.06,
        "number_operators": 23,
        "number_operands": 60,
        "number_operators_unique": 6,
        "number_operands_unique": 18,
        "cloc": 0,
        "loc": 51,
        "lloc": 51,
        "mi": 43.61,
        "mIwoC": 43.61,
        "commentWeight": 0,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.53,
        "relativeSystemComplexity": 64.53,
        "totalStructuralComplexity": 320,
        "totalDataComplexity": 2.67,
        "totalSystemComplexity": 322.67,
        "package": "Orders\\Domain\\Entities\\",
        "pageRank": 0.22,
        "afferentCoupling": 11,
        "efferentCoupling": 8,
        "instability": 0.42,
        "violations": {}
    },
    {
        "name": "Orders\\Domain\\ValueObjects\\OrderStatusTransitions",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "canTransition",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Orders\\Domain\\ValueObjects\\OrderStatus",
            "Orders\\Domain\\ValueObjects\\OrderStatus"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 25,
        "vocabulary": 13,
        "volume": 92.51,
        "difficulty": 3.3,
        "effort": 305.29,
        "level": 0.3,
        "bugs": 0.03,
        "time": 17,
        "intelligentContent": 28.03,
        "number_operators": 3,
        "number_operands": 22,
        "number_operators_unique": 3,
        "number_operands_unique": 10,
        "cloc": 0,
        "loc": 10,
        "lloc": 10,
        "mi": 64.15,
        "mIwoC": 64.15,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 3,
        "package": "Orders\\Domain\\ValueObjects\\",
        "pageRank": 0.04,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Orders\\Domain\\ValueObjects\\Address",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getStreetType",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getStreetName",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getNumber",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getComplement",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDistrict",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCity",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getState",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getZipCode",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toArray",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromArray",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 11,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 8,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "Orders\\Domain\\Validation\\ValidationHelper",
            "Orders\\Domain\\Validation\\ValidationHelper",
            "InvalidArgumentException"
        ],
        "parents": [],
        "implements": [],
        "lcom": 3,
        "length": 96,
        "vocabulary": 22,
        "volume": 428.11,
        "difficulty": 6.63,
        "effort": 2839.01,
        "level": 0.15,
        "bugs": 0.14,
        "time": 158,
        "intelligentContent": 64.56,
        "number_operators": 12,
        "number_operands": 84,
        "number_operators_unique": 3,
        "number_operands_unique": 19,
        "cloc": 0,
        "loc": 54,
        "lloc": 54,
        "mi": 43.25,
        "mIwoC": 43.25,
        "commentWeight": 0,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 3.61,
        "relativeSystemComplexity": 7.61,
        "totalStructuralComplexity": 44,
        "totalDataComplexity": 39.67,
        "totalSystemComplexity": 83.67,
        "package": "Orders\\Domain\\ValueObjects\\",
        "pageRank": 0.07,
        "afferentCoupling": 3,
        "efferentCoupling": 2,
        "instability": 0.4,
        "violations": {}
    },
    {
        "name": "Orders\\Domain\\ValueObjects\\Item",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getProductId",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getQuantity",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPrice",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "calculateSubtotal",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toArray",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromArray",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 3,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "InvalidArgumentException",
            "InvalidArgumentException"
        ],
        "parents": [],
        "implements": [],
        "lcom": 3,
        "length": 40,
        "vocabulary": 15,
        "volume": 156.28,
        "difficulty": 5.27,
        "effort": 824,
        "level": 0.19,
        "bugs": 0.05,
        "time": 46,
        "intelligentContent": 29.64,
        "number_operators": 11,
        "number_operands": 29,
        "number_operators_unique": 4,
        "number_operands_unique": 11,
        "cloc": 0,
        "loc": 37,
        "lloc": 37,
        "mi": 50.03,
        "mIwoC": 50.03,
        "commentWeight": 0,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 6.57,
        "relativeSystemComplexity": 6.57,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 46,
        "totalSystemComplexity": 46,
        "package": "Orders\\Domain\\ValueObjects\\",
        "pageRank": 0.01,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    }
]